# Generated by Django 2.1.7 on 2019-03-12 22:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='todoDB',
            new_name='email',
        ),
    ]
